version: '2'
services:
    researchrepositorylearningsystem-app:
        image: researchrepositorylearningsystem
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://researchrepositorylearningsystem-mysql:3306/researchrepositorylearningsystem?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    researchrepositorylearningsystem-mysql:
        extends:
            file: mysql.yml
            service: researchrepositorylearningsystem-mysql
